"""empty message

Revision ID: fd5167caf34a
Revises: dd44a0a56416
Create Date: 2024-10-17 03:25:39.006459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5167caf34a'
down_revision = 'dd44a0a56416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_time', sa.DateTime(), nullable=False),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('response_time', sa.DateTime(), nullable=False),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    # ### end Alembic commands ###
