"""Add score field to Rubric

Revision ID: 4e8897bac916
Revises: fd5167caf34a
Create Date: 2024-11-19 03:23:42.662165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8897bac916'
down_revision = 'fd5167caf34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubric', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
